### PR TITLE
[BUGFIX] [FEATURE] Avoid error in install tool + new extension configuration option

### PR DESCRIPTION
**Pull request by rafu1987**
Avoid error in install tool:

Error: BLOB/TEXT column 'source_path' used in key specification without a key length

### CODE REVIEW

**Comment by rafu1987** [comment]
GitHub won't let me edit my first comment, so here's the explanation :-)

**Avoid error in install tool:**
Error: BLOB/TEXT column 'source_path' used in key specification without a key length

**New extension configuration setting:**
Only create redirects in **production** application context or if the extension setting is deactivated. The idea was to not create redirects in development stage, because you don't really need them, before going live with the site and the sys_redirects table won't bloat.

**Comment by wazum** [comment]
@rafu1987 thanks for your feedback and the pull request. I already had plans to remove the dependency on redirects and the feature to activate/deactivate redirects on demand is nice too. 
I incorporated all your changes in a different form, so please test with the latest `dev-master`.
Afterwards we can abandon this pull request. Thanks again!

**Comment by rafu1987** [comment]
Everything works fine, except I'm still getting the error:

`Error: BLOB/TEXT column 'source_path' used in key specification without a key length`

**Comment by wazum** [comment]
I adapted the definitions again (they were changed in a recent version of `typo3/cms-redirects`), I think I can't do anything else then (Core sets the index, sluggi does too).

**Comment by rafu1987** [comment]
Thanks for the changes, but I'm still getting the same error.

The field change looks like this in TYPO3 9.5.x:

```
ALTER TABLE `sys_redirect` CHANGE `source_path` `source_path` VARCHAR(2048) DEFAULT '' NOT NULL 
Current value: source_path VARCHAR(255) DEFAULT '' NOT NULL COLLATE utf8_unicode_ci
```

Do you need to set VARCHAR(2048) or wouldn't VARCHAR(255) suffice, as it's set in the core?

**Comment by wazum** [comment]
@rafu1987 looks like you have some older version, as the redirects extension (9.5.10) uses `VARCHAR(2048)` right now.
And yes, 255 is not enough for most of URL strings.

**Pull request closed without merging**
